# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source $HOME/opt/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $HOME/opt/zsh-history-substring-search/zsh-history-substring-search.zsh
source $HOME/opt/zsh-autosuggestions/zsh-autosuggestions.zsh
# keybindings for substring-search
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down
bindkey '^b' autosuggest-accept
bindkey '^ ' autosuggest-execute

# fuzzy file search
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# add dir with symlinks
export PATH=$PATH:~/bin/
export PATH=$PATH:~/.local/bin/

# set neovim as the default editor
export EDITOR='nv'
export VISUAL='nv'

# Git aliases
alias gs='git status -s'
alias gd='git diff'
alias ga='git add'
alias gau='git add --update'
alias gc='git commit -v'
alias gca='git commit -v -a'

# Kubernetes alias
alias k='kubectl'

# Neovim + AI chat assistant alias
alias nvchat='nv -c "PrtChatNew"'

# disable system flow control (free Ctrl+V)
# stty -ixon
# instead of stty -ixon, use the following to unbind ^V
bindkey -r '^V'

# set up npm global packages (https://docs.anthropic.com/en/docs/claude-code/troubleshooting#recommended-solution-create-a-user-writable-npm-prefix)
export PATH=~/opt/npm-global/bin:$PATH

# opencode
export PATH=$HOME/.opencode/bin:$PATH

