#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('$HOME/opt/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/opt/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/opt/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/opt/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

source $HOME/opt/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $HOME/opt/zsh-history-substring-search/zsh-history-substring-search.zsh
source $HOME/opt/zsh-autosuggestions/zsh-autosuggestions.zsh
# keybindings for substring-search
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down

# Enable .dotfile tracking in $HOME.
# Based on https://www.atlassian.com/git/tutorials/dotfiles
# and https://news.ycombinator.com/item?id=11071754
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
config config --local status.showUntrackedFiles no
# echo "alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'"

# AFNI
export PATH=$PATH:$HOME/abin/
# add afni Roi Average plugin
export AFNI_ALLOW_ROIAVERAGE_PLUGIN=YES

# fuzzy file search
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# add dir with symlinks
export PATH=$PATH:~/bin/
export PATH=$PATH:~/.local/bin/

# set neovim as the default editor
export EDITOR='nv'

# Git aliases
alias gs='git status -s'
alias gd='git diff'
alias ga='git add'
alias gau='git add --update'
alias gc='git commit -v'
alias gca='git commit -v -a'
